name: General CI

on: push

jobs:
  build:
    strategy:
      matrix:
        java-version: [8, 11, 17]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - run: mvn --batch-mode package
