name: Main CI

on:
  push:
    branches-ignore:
      - 'master'
    paths-ignore:
      - '.github/workflows/native.yml'
      - '.mvn/**'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'mvnw'
      - 'mvnw.cmd'

jobs:
  build:
    strategy:
      matrix:
        java-version: [8, 11, 17, 21]

    name: java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - run: mvn --batch-mode package
