name: Native CI

on:
  push:
    branches-ignore:
      - 'master'
    paths-ignore:
      - '.github/workflows/main.yml'
      - '.mvn/**'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'mvnw'
      - 'mvnw.cmd'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - run: mvn -Pnative --batch-mode package
